stages:
  - test
  - publish

before_script:
  - ./gradlew --version
  - which javac
  - javac -version
  - which java
  - java -version

test:
  stage: test
  script:
  - ./gradlew clean build test --info --rerun-tasks
  artifacts:
    paths:
    - build/
    when: always
    expire_in: 2 weeks

publish:
  stage: publish
  script:
  - ./gradlew clean releaseCurrVersion --info --rerun-tasks
  artifacts:
    paths:
    - build/
    when: always
  only:
  - master
